// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvuAgQBl8UfrTn-E4NL4TmL131Flke8pw',
    appId: '1:125186098692:web:1437464d0874de8b6b5751',
    messagingSenderId: '125186098692',
    projectId: 'lapp-2340e',
    authDomain: 'lapp-2340e.firebaseapp.com',
    storageBucket: 'lapp-2340e.firebasestorage.app',
    measurementId: 'G-1LJQY5WXE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvviixpdqTrJRba_f33MPRhZp84iTiEw',
    appId: '1:125186098692:android:62225fde8b9aa9586b5751',
    messagingSenderId: '125186098692',
    projectId: 'lapp-2340e',
    storageBucket: 'lapp-2340e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcAbxHrydCbRG3Cs3Fc8dFS9hjHnDydrk',
    appId: '1:125186098692:ios:0878e0665d664bd66b5751',
    messagingSenderId: '125186098692',
    projectId: 'lapp-2340e',
    storageBucket: 'lapp-2340e.firebasestorage.app',
    iosBundleId: 'com.example.lapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcAbxHrydCbRG3Cs3Fc8dFS9hjHnDydrk',
    appId: '1:125186098692:ios:0878e0665d664bd66b5751',
    messagingSenderId: '125186098692',
    projectId: 'lapp-2340e',
    storageBucket: 'lapp-2340e.firebasestorage.app',
    iosBundleId: 'com.example.lapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvuAgQBl8UfrTn-E4NL4TmL131Flke8pw',
    appId: '1:125186098692:web:f9f045833105f4306b5751',
    messagingSenderId: '125186098692',
    projectId: 'lapp-2340e',
    authDomain: 'lapp-2340e.firebaseapp.com',
    storageBucket: 'lapp-2340e.firebasestorage.app',
    measurementId: 'G-5CSKLGD15Y',
  );
}
